require('dotenv').config();
const express = require('express');
const cors = require('cors');
const axios = require('axios');
const { OpenAI } = require('openai');
const PDFDocument = require('pdfkit'); // 📄 PDF support

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// ENV Keys
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;

// Gemini API URL - YAHAN GALTI THEEK KI GAYI HAI
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`;

// OpenRouter Client
const openai = new OpenAI({
    apiKey: OPENROUTER_API_KEY,
    baseURL: 'https://openrouter.ai/api/v1',
});

// ✨ Unified AI Response Generator
async function generateAIResponse(prompt, context) {
    const fullPrompt = `${context}\n\n${prompt}`.trim();

    // Try OpenRouter First
    try {
        const completion = await openai.chat.completions.create({
            model: 'deepseek/deepseek-r1-0528-qwen3-8b:free',
            messages: [
                { role: 'system', content: context },
                { role: 'user', content: prompt }
            ],
            extra_headers: {
                'HTTP-Referer': 'https://your-frontend.site', // <-- Ise apne site URL se badal lein
                'X-Title': 'SahilAssignmentAI'
            }
        });

        const result = completion.choices[0].message.content;
        return { text: result, source: 'openrouter' };

    } catch (error) {
        console.warn('⚠️ OpenRouter failed. Trying Gemini...', error.message);
    }

    // Fallback to Gemini
    try {
        const response = await axios.post(GEMINI_API_URL, {
            contents: [{ parts: [{ text: fullPrompt }] }],
            generationConfig: {
                temperature: 0.7,
                topP: 0.95,
                topK: 40,
                maxOutputTokens: 2048
            },
            safetySettings: [
                { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_ONLY_HIGH" },
                { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_ONLY_HIGH" }
            ]
        });

        const result = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
        return { text: result || 'No result from Gemini.', source: 'gemini' };

    } catch (error) {
        console.error('❌ Gemini API Error:', error.message);
        throw new Error('Both AI services failed.');
    }
}

// 📄 PDF Generator Function
function generatePDF(content, res) {
    const doc = new PDFDocument();
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=output.pdf');

    doc.pipe(res);
    doc.font('Times-Roman').fontSize(14);
    doc.text(content);
    doc.moveDown();
    doc.fontSize(10).fillColor('gray').text('\nGenerated by SahilCodeLab', { align: 'center' });
    doc.end();
}

// 🚀 Assignment Endpoint
app.post('/generate-assignment', async (req, res) => {
    try {
        const { prompt } = req.body;
        if (!prompt) return res.status(400).json({ error: "Prompt is required" });

        const context = `
You are a professional academic content writer. Your task is to generate a complete, well-structured, and original assignment of 9-10 pages (minimum 3500-4000 words) on any given topic.

Follow these exact guidelines while writing:

1. **Title Page**:
   - Assignment Title
   - Student Name (use placeholder if not provided)
   - Subject Name
   - Submission Date

2. **Table of Contents**:
   - Auto-generate TOC for all main sections and sub-sections.

3. **Introduction**:
   - Brief overview of the topic
   - Purpose of the assignment
   - Scope and relevance of the subject

4. **Main Body (At least 6 detailed sections)**:
   Include the following points (if relevant to topic):
   - Historical background
   - Definitions and key concepts
   - Importance of the topic
   - Current status / trends
   - Challenges or issues
   - Case studies or examples
   - Future scope or developments
   - Role in society/education/technology/etc.

5. **Data & Visuals** (Optional):
   - Mention possible charts, stats, tables (describe them if can't display)

6. **Conclusion**:
   - Summary of key points
   - Final thoughts or opinion
   - Recommendations (if applicable)

7. **References**:
   - Use at least 5 references (can be made-up if not real)
   - Follow any consistent citation format (APA, MLA, etc.)

📝 Writing Rules:
- Use formal academic tone and structured formatting.
- Avoid plagiarism — everything must be original.
- Use proper paragraphs, headings, and bullet points.
- Make it easy to read, yet deeply informative.
- Output should feel like a real college-level or university-level assignment.

`.trim();


        const result = await generateAIResponse(prompt, context);
        if (req.query.download === 'pdf') return generatePDF(result.text, res);
        res.json(result);

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// 🧠 Short Answer Endpoint
app.post('/generate-short-answer', async (req, res) => {
    try {
        const { prompt } = req.body;
        if (!prompt) return res.status(400).json({ error: "Prompt is required" });

        const context = `Provide a concise 2-3 sentence answer to the question...`;

        const result = await generateAIResponse(prompt, context);
        res.json(result);

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// 📚 Long Answer Endpoint
app.post('/generate-long-answer', async (req, res) => {
    try {
        const { prompt } = req.body;
        if (!prompt) return res.status(400).json({ error: "Prompt is required" });

        const context = `Provide a detailed 300-500 word explanation...`;

        const result = await generateAIResponse(prompt, context);
        if (req.query.download === 'pdf') return generatePDF(result.text, res);
        res.json(result);

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// 🔍 Health Check
app.get('/health', (req, res) => {
    res.status(200).json({ status: 'healthy', fallback: 'openrouter -> gemini' });
});

// 🌐 Start Server
app.listen(PORT, () => {
    console.log(`🚀 Server running on http://localhost:${PORT}`);
    console.log(`🔌 Fallback AI ready: OpenRouter > Gemini`);
});
