require('dotenv').config();
const express = require('express');
const cors = require('cors');
const axios = require('axios');
const { OpenAI } = require('openai');
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.static('public')); // For serving static files

// ENV Keys
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;

// Gemini API URL
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`;

// OpenRouter Client
const openai = new OpenAI({
    apiKey: OPENROUTER_API_KEY,
    baseURL: 'https://openrouter.ai/api/v1',
});

// ✨ Unified AI Response Generator
async function generateAIResponse(prompt, context) {
    const fullPrompt = `${context}\n\n${prompt}`.trim();

    // Try OpenRouter First
    try {
        const completion = await openai.chat.completions.create({
            model: 'deepseek/deepseek-r1-0528-qwen3-8b:free',
            messages: [
                { role: 'system', content: context },
                { role: 'user', content: prompt }
            ],
            extra_headers: {
                'HTTP-Referer': 'https://your-frontend.site',
                'X-Title': 'SahilAssignmentAI'
            }
        });

        const result = completion.choices[0].message.content;
        return { text: result, source: 'openrouter' };

    } catch (error) {
        console.warn('⚠️ OpenRouter failed. Trying Gemini...', error.message);
    }

    // Fallback to Gemini
    try {
        const response = await axios.post(GEMINI_API_URL, {
            contents: [{ parts: [{ text: fullPrompt }] }],
            generationConfig: {
                temperature: 0.7,
                topP: 0.95,
                topK: 40,
                maxOutputTokens: 2048
            },
            safetySettings: [
                { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_ONLY_HIGH" },
                { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_ONLY_HIGH" }
            ]
        });

        const result = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
        return { text: result || 'No result from Gemini.', source: 'gemini' };

    } catch (error) {
        console.error('❌ Gemini API Error:', error.message);
        throw new Error('Both AI services failed.');
    }
}

// 📄 Premium PDF Generator Function
function generatePremiumPDF(content, res, userDetails = {}) {
    const doc = new PDFDocument({
        margin: 50,
        size: 'A4',
        bufferPages: true // Important for page numbers
    });

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=premium_assignment.pdf');

    // Pipe PDF to response
    doc.pipe(res);

    // Custom colors
    const colors = {
        primary: '#3498db',
        secondary: '#2c3e50',
        accent: '#e74c3c',
        text: '#333333',
        lightGray: '#f5f5f5'
    };

    // 📌 Watermark and Page Number Setup
    doc.on('pageAdded', () => {
        // Watermark (on every page)
        doc.fillColor('#e0e0e0')
            .fontSize(60)
            .rotate(-45, { origin: [doc.page.width / 2, doc.page.height / 2] })
            .opacity(0.1)
            .text('Generated by SahilCodeLab', doc.page.width / 2 - 150, doc.page.height / 2, {
                align: 'center',
                width: 300
            })
            .rotate(45, { origin: [doc.page.width / 2, doc.page.height / 2] })
            .opacity(1);

        // Page number (footer right)
        const pageNumber = doc.bufferedPageRange().count;
        doc.fillColor(colors.text)
            .fontSize(10)
            .text(`Page ${pageNumber}`, doc.page.width - 50, doc.page.height - 30, {
                align: 'right'
            });
    });

    // Trigger first page
    doc.addPage();

    // 🎨 Cover Page Design
    doc.rect(0, 0, doc.page.width, doc.page.height).fill(colors.lightGray);
    
    // Title Box
    doc.rect(50, 150, doc.page.width - 100, 120)
        .fill(colors.primary)
        .fillColor('white')
        .fontSize(28)
        .font('Helvetica-Bold')
        .text('ASSIGNMENT', 50, 180, {
            width: doc.page.width - 100,
            align: 'center'
        });
    
    // Topic
    doc.fillColor(colors.secondary)
        .fontSize(20)
        .text(content.split('\n')[0].replace('#', '').trim(), 50, 250, {
            width: doc.page.width - 100,
            align: 'center'
        });
    
    // Decorative line
    doc.moveTo(50, 300)
        .lineTo(doc.page.width - 50, 300)
        .stroke(colors.accent)
        .lineWidth(2);
    
    // Student details
    doc.fillColor(colors.text)
        .fontSize(14)
        .text(`Prepared by: ${userDetails.name || '[Student Name]'}`, 50, 320, {
            width: doc.page.width - 100,
            align: 'center'
        })
        .text(`Course: ${userDetails.course || '[Course Name]'}`, 50, 350, {
            width: doc.page.width - 100,
            align: 'center'
        })
        .text(`Date: ${userDetails.date || new Date().toLocaleDateString()}`, 50, 380, {
            width: doc.page.width - 100,
            align: 'center'
        });
    
    // Footer note
    doc.fontSize(10)
        .text('Generated by SahilCodeLab', 50, doc.page.height - 50, {
            width: doc.page.width - 100,
            align: 'center'
        });
    
    doc.addPage();

    // 📑 Table of Contents
    doc.fillColor(colors.secondary)
        .fontSize(18)
        .font('Helvetica-Bold')
        .text('TABLE OF CONTENTS', { align: 'center' });
    
    doc.moveDown();
    
    // Generate TOC from headings
    const headings = content.split('\n').filter(line => line.startsWith('##'));
    headings.forEach(heading => {
        doc.fillColor(colors.primary)
            .font('Helvetica')
            .fontSize(12)
            .text(heading.replace('##', '').trim(), {
                indent: 20,
                continued: true
            })
            .fillColor(colors.text)
            .text('.........................', {
                continued: true,
                align: 'right'
            })
            .text(doc.bufferedPageRange().count + 1, {
                align: 'right'
            });
        doc.moveDown(0.5);
    });

    // 📝 Main Content
    doc.addPage();
    let currentSection = '';
    
    content.split('\n').forEach(line => {
        // Page break if near bottom
        if (doc.y > doc.page.height - 100) {
            doc.addPage();
        }
        
        if (line.startsWith('##')) {
            // Major section heading
            currentSection = line.replace('##', '').trim();
            doc.fillColor(colors.secondary)
                .font('Helvetica-Bold')
                .fontSize(16)
                .text(currentSection, {
                    align: 'left'
                });
            doc.moveDown();
        } else if (line.startsWith('###')) {
            // Subsection heading
            doc.fillColor(colors.primary)
                .font('Helvetica-Bold')
                .fontSize(14)
                .text(line.replace('###', '').trim(), {
                    align: 'left'
                });
            doc.moveDown();
        } else if (line.trim() !== '') {
            // Regular content
            doc.fillColor(colors.text)
                .font('Times-Roman')
                .fontSize(12)
                .text(line.trim(), {
                    align: 'justify',
                    lineGap: 5,
                    paragraphGap: 8,
                    indent: 20
                });
            doc.moveDown();
        }
    });

    // 📚 References Page
    doc.addPage();
    doc.fillColor(colors.secondary)
        .font('Helvetica-Bold')
        .fontSize(16)
        .text('REFERENCES', { align: 'center' });
    
    doc.moveDown();
    
    // Sample references (in real app, extract from content)
    const references = [
        "Author, A. (Year). Title of work. Publisher.",
        "Researcher, B. (Year). Article title. Journal Name, volume(issue), page range.",
        "Writer, C. (Year). Book title. City: Publisher.",
        "Scholar, D. (Year). Paper title. Conference Proceedings.",
        "Expert, E. (Year). Online resource. Retrieved from URL"
    ];
    
    references.forEach((ref, i) => {
        doc.fillColor(colors.text)
            .font('Times-Roman')
            .fontSize(11)
            .text(`${i + 1}. ${ref}`, {
                indent: 20
            });
        doc.moveDown(0.5);
    });

    doc.end();
}

// 🚀 Assignment Endpoint (Two-step process)
app.post('/generate-assignment', async (req, res) => {
    try {
        const { prompt, userDetails } = req.body;
        if (!prompt) return res.status(400).json({ error: "Prompt is required" });

        const context = `
You are a professional academic writer.

🎯 Your task: Write a complete, clear, well-structured assignment of 9–10 pages (minimum 4000 words) on the following topic: "{{TOPIC}}"

📘 Structure:
1. **Title Page**
   - Assignment Title
   - Student Name: [Placeholder]
   - Subject Name: [Placeholder]
   - Submission Date: [Placeholder]

2. **Table of Contents**
   - Auto-generate section-wise TOC (include page numbers approx.)

3. **Introduction**
   - Briefly introduce the topic
   - Purpose of the assignment
   - Scope & relevance of the topic

4. **Main Body** (At least 6 sections):
   - Definitions & key concepts
   - Historical background
   - Importance of the topic
   - Current trends or status
   - Challenges / problems
   - Case studies or real-world examples
   - Future possibilities
   - Role in society, education, tech, etc.

5. **Data & Visuals (Optional)**
   - Describe charts or tables if needed (don't embed images)

6. **Conclusion**
   - Summary of all key points
   - Final thoughts or opinions
   - Any recommendations

7. **References**
   - Include 5 citations in APA format (can be fictional but realistic)

📝 Writing Rules:
- Use formal, academic tone (college/university level)
- Organize with clear headings and paragraphs
- Avoid any corrupted characters or unreadable formatting
- No plagiarism; completely original writing
- Focus on clarity, logic, and deep insights

📌 Output format:
- Use Markdown with headers (##, ###)
- Avoid using bold/italic inside text unless needed
- Use bullet points, numbered lists where appropriate
`.trim();

        const result = await generateAIResponse(prompt, context);
        
        // Save the generated content temporarily (in a real app, use database)
        const contentId = Date.now().toString();
        const tempDir = path.join(__dirname, 'temp');
        if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir);
        fs.writeFileSync(path.join(tempDir, `${contentId}.json`), JSON.stringify({
            content: result.text,
            userDetails: userDetails || {}
        }));
        
        res.json({
            ...result,
            contentId,
            downloadUrl: `/download-pdf/${contentId}`
        });

    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// 📥 PDF Download Endpoint
app.get('/download-pdf/:contentId', (req, res) => {
    try {
        const contentId = req.params.contentId;
        const tempDir = path.join(__dirname, 'temp');
        const filePath = path.join(tempDir, `${contentId}.json`);
        
        if (!fs.existsSync(filePath)) {
            return res.status(404).json({ error: "Content not found or expired" });
        }
        
        const { content, userDetails } = JSON.parse(fs.readFileSync(filePath));
        generatePremiumPDF(content, res, userDetails);
        
        // Clean up (in production, use proper storage)
        fs.unlinkSync(filePath);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// Other endpoints remain the same...

// 🌐 Start Server
app.listen(PORT, () => {
    console.log(`🚀 Server running on http://localhost:${PORT}`);
    console.log(`🔌 Fallback AI ready: OpenRouter > Gemini`);
});